steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/praveen-space/election-assistant', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/praveen-space/election-assistant']
images:
  - 'gcr.io/praveen-space/election-assistant'